### PR TITLE
Added Gradle and Maven builds, prettified README.md

### PR DESCRIPTION
**Pull request by badlogic**
Hope the "product placement" is OK in the README.md. As a small company we need to make things count :)

### CODE REVIEW

**Comment by badlogic** [comment]
Added a small optimization that brings us closer to the top 3. Our floating point modulo is currently using the libm intrinsic which is quite slow for 64-bit floats on ARM. We need to optimize that on our end. For now, i replaced the modulos in `Point.java` with the equivalent div/mul form.

Also, kudos for using greek literals in `Point.java`. That was a first for me :)

**Comment by harrycheung** [comment]
We live in a UTF8 world now, why not? Actually, they came from code I cut-and-pasted from some gps coordinate manipulations I found. It made it easier to debug since I would compare line by line.

**Comment by badlogic** [comment]
Totally agree, makes the code a lot easier to read for the mathematically
minded. Thanks for the merge!

**Comment by harrycheung** [comment]
But it's a pain in the ass to type.

By the way, any chance the unit tests work for you after this change? It's
not working for me so maybe the merge wasn't whole.

**Comment by badlogic** [comment]
My optimization was broken. Reverted, see #10 . We'll have to live with our "poor" performance for now :)

**Comment by harrycheung** [comment]
Actually, I just added a int cast so
```
A % B = A - B * (int)(A / B)
```
right?

**Comment by harrycheung** [comment]
Ah, but that's comes out expensive too.

**Comment by badlogic** [comment]
And it's not entirely correct. It needs to be a floor operation, which has even worse performance than the cast :)

**Pull request merged**
